<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>File Upload</title>
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit">Send</button>
        </form>
        <?php
            if (isset($info)) {
                ?>
                    <p><?= $info ?></p>
                <?php
            }
        ?>
    </body>
</html>
